import LZString from "lz-string";

// ─── Sampler-config sharing ───────────────────────────────────────────────────
// Serialize the *minimal* sampler config into a URL-safe blob and back. The app is
// hosted statically (GitHub Pages, no backend), so the whole config rides in the URL.
// Only the authoring inputs travel — never ephemeral output (drawn rows, collected
// statistics, animation/UI state), which are regenerated by re-running the sampler.

// Bump when the serialized SHAPE changes incompatibly; decode rejects unknown majors.
const VERSION = 1;

// Pull the shareable fields out of full app state (everything else is derived/ephemeral).
function pickConfig(state) {
  return {
    pipeline: state.pipeline,
    sampleSize: state.sampleSize,
    runMode: state.runMode,
    stopRule: state.stopRule,
    trackedStats: state.trackedStats,
    codeLang: state.codeLang,        // Task E (undefined-safe before it lands)
  };
}

// ─── Hidden (password-veiled) helpers — NOT crypto-grade ──────────────────────
// Just enough to deter casual peeking at a shared population sampler. The plaintext
// password never travels; only the salt and the XOR'd blob do. Wrong password ⇒ the
// inner decompress fails on garbage ⇒ decode returns null ("incorrect password").
function deriveKey(password, salt) {
  // Cheap, dependency-free key stretch: FNV-style fold of password+salt into a fixed
  // 64-char printable-ASCII keystream. (Deterministic; not a KDF — see note above.)
  const seed = password + "::" + salt;
  let h = 2166136261 >>> 0;
  let out = "";
  for (let i = 0; i < 64; i++) {
    h ^= seed.charCodeAt(i % seed.length) || 0;
    h = Math.imul(h, 16777619) >>> 0;
    out += String.fromCharCode(33 + (h % 94)); // printable ASCII, < 128
  }
  return out;
}
// XOR each char against the repeating key. Operates on base64 text (chars < 128) so the
// result stays < 128 (plain ASCII, possibly control chars) and survives JSON round-trips.
function xorCipher(str, key) {
  let out = "";
  for (let i = 0; i < str.length; i++) out += String.fromCharCode(str.charCodeAt(i) ^ key.charCodeAt(i % key.length));
  return out;
}
function randomSalt() {
  return Math.random().toString(36).slice(2, 10);
}

// Encode app state → a URL-safe blob string (the value of the ?s= param).
// opts.password (optional) produces a HIDDEN blob: the config is concealed behind the
// password while the sampler still runs for whoever opens the link.
export function encodeConfig(state, opts) {
  const config = pickConfig(state);
  const password = opts && opts.password;
  let envelope;
  if (password) {
    const salt = randomSalt();
    const inner = LZString.compressToBase64(JSON.stringify(config));
    const data = xorCipher(inner, deriveKey(password, salt));
    envelope = { v: VERSION, hidden: true, salt, data };
  } else {
    envelope = { v: VERSION, hidden: false, config };
  }
  return LZString.compressToEncodedURIComponent(JSON.stringify(envelope));
}

// Decode a blob → one of:
//   null                              (absent/garbled/unsupported version)
//   { hidden:false, config }          (ready to load)
//   { hidden:true, salt, data }       (caller must prompt for a password, then call
//                                       decodeHidden(salt, data, password))
export function decodeConfig(blob) {
  if (!blob) return null;
  let envelope;
  try {
    const json = LZString.decompressFromEncodedURIComponent(blob);
    if (!json) return null;
    envelope = JSON.parse(json);
  } catch { return null; }
  if (!envelope || envelope.v !== VERSION) return null;
  if (envelope.hidden) {
    if (!envelope.salt || !envelope.data) return null;
    return { hidden: true, salt: envelope.salt, data: envelope.data };
  }
  if (!envelope.config || !Array.isArray(envelope.config.pipeline)) return null;
  return { hidden: false, config: envelope.config };
}

// Reverse a hidden blob with the password. Returns the config, or null on a wrong
// password (the XOR'd bytes decompress to garbage → null).
export function decodeHidden(salt, data, password) {
  try {
    const inner = xorCipher(data, deriveKey(password, salt));
    const json = LZString.decompressFromBase64(inner);
    if (!json) return null;
    const config = JSON.parse(json);
    if (!config || !Array.isArray(config.pipeline)) return null;
    return config;
  } catch { return null; }
}

// Build a full shareable URL for the current page from a blob.
export function shareURL(blob) {
  const base = window.location.origin + window.location.pathname;
  return base + "?s=" + blob;
}
