import LZString from "lz-string";
import { uid, COLORS } from "./util.js";

// ─── Sampler-config sharing ───────────────────────────────────────────────────
// Serialize the *minimal* sampler config into a URL-safe blob and back. The app is
// hosted statically (GitHub Pages, no backend), so the whole config rides in the URL.
// Only the authoring inputs travel — never ephemeral output (drawn rows, collected
// statistics, animation/UI state), which are regenerated by re-running the sampler.
//
// SIZE IS THE DESIGN CONSTRAINT. A link gets pasted into a syllabus, an email, or an LMS,
// so the payload is minified HARD before it is compressed — the compressor can only mask
// verbosity, not remove it. Hence the tuple form below: no ids, no key names, no defaults,
// mixer balls run-length grouped. This is what keeps a typical link ~110 chars instead of
// ~530, and a hidden one ~110 instead of ~2200.
//
// FORMAT (v2). The blob's FIRST CHAR is a marker we author, so plain vs hidden vs a stale
// v1 link is unambiguous without guessing:
//   "P" + lz                                   plain
//   "H" + salt(8) + verifier(12) + xorAlpha(lz)  hidden
// where lz = compressToEncodedURIComponent(JSON.stringify(compact)) and compact is:
//   [ pipeline, opts? ]
//   stage   : [ varName, [branch, ...] ]
//   branch  : [ device ] | [ device, upstreamStageIndex, condVal ]
//   device  : [ typeCode, wr, entries, extra? ]
//   entries : [ [label, pctOrCount, color], ... ]     color = COLORS index, else "#rrggbb"
//   extra   : { o?: ballOrder, v?: deviceVarName }     both omitted when derivable
//   opts    : { n?, u?, r?, l? }                       omitted entirely when all default
// v2 is a CLEAN BREAK: v1 blobs are detected and reported stale, not decoded.

// Code-known obfuscation key (NOT a secret). A hidden link's config is XOR'd with a key
// derived from this + the salt so a casual decompress of the URL shows garbage — but the
// app can always decode it, so the sampler runs for anyone who opens the link. The user's
// password is never needed to RUN a hidden sampler, only to REVEAL its contents.
const PEPPER = "tinkersim-veil-v1";
// lz-string's URI-safe output alphabet. xorAlpha veils WITHIN this alphabet so the result
// stays URL-safe with no base64/escaping round-trip (see the hidden note below).
const ALPHA = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+-$";
// How much of the password verifier rides in the URL. Truncated purely for length; the
// scheme was never crypto-grade (see below), so the shorter prefix costs nothing real.
const PW_LEN = 12;

const TYPES = ["spinner", "stacks", "mixer"];
const STOP_KINDS = ["outcome", "count", "distinct"];
const DEFAULT_N = 10;

// Pull the shareable fields out of full app state (everything else is derived/ephemeral).
// Only sampler *authoring* travels — never collected/selected output like trackedStats,
// which are regenerated by re-running the shared sampler. (That omission is also what lets
// the encoder drop ids entirely: nothing outside the pipeline references them.)
//
// A device filled from a CSV column carries a `source:{dataset,var}` link (so the live code
// panel can emit read.csv). But the recipient of a shared link has no CSV — so we strip
// `source` here, hard-coding the data: the literal items/balls already populated by the fill
// stay, the sampler runs identically, and generated code inlines a literal vector (no read.csv).
// Also drop `rowSample` (the embedded dataset snapshot of a row-resampling mixer): the UI
// already disables sharing for those samplers, and a snapshot would bloat/break the URL. This
// is a defensive strip so a stray encode can never embed a dataset.
function stripSource(pipeline) {
  return (pipeline || []).map(st => ({
    ...st,
    branches: (st.branches || []).map(b => {
      if (!b.device || (!b.device.source && !b.device.rowSample)) return b;
      const { source, rowSample, ...device } = b.device;
      return { ...b, device };
    }),
  }));
}

// ─── Compact pipeline codec ───────────────────────────────────────────────────
// Colors are almost always straight from the palette, so store the index (1-2 chars) and
// keep the literal hex only for an off-palette custom pick.
const encColor = c => { const i = COLORS.indexOf(c); return i >= 0 ? i : c; };
const decColor = c => (typeof c === "number" ? COLORS[c] || COLORS[0] : c);
// 33.333333333333336 → 33.3333 (17 chars → 7). Harmless: sampleSpinner normalizes by the
// running total, so the dropped residual divides out.
const round4 = x => Math.round((Number(x) || 0) * 1e4) / 1e4;

// A mixer is a multiset of balls and its editor is already label-grouped, so store
// [label, count, color] groups. But ball ORDER is visible (a mixer pasted from a CSV column
// is interleaved, and reopening it reclumped by color would be a real change), so when the
// balls aren't already contiguous by group, also store the order — a base36 digit per ball,
// or a plain index array in the rare >36-group case.
function encBalls(balls) {
  const groups = [];
  // Color first: its token is a number or "#rrggbb" and never contains a space, so this is
  // injective even for a label that has spaces in it (label-first would not be).
  const key = b => encColor(b.color) + " " + b.label;
  const index = new Map();
  const order = [];
  for (const b of balls || []) {
    const k = key(b);
    if (!index.has(k)) { index.set(k, groups.length); groups.push([b.label, 0, encColor(b.color)]); }
    const gi = index.get(k);
    groups[gi][1]++;
    order.push(gi);
  }
  // Contiguous ⇒ expanding the groups in order rebuilds the exact sequence, so order is free.
  // Each group's balls must form one unbroken run: revisiting a group we already left breaks it.
  let contiguous = true;
  const seen = new Set();
  let prev = -1;
  for (const gi of order) {
    if (gi !== prev && seen.has(gi)) { contiguous = false; break; }
    seen.add(gi); prev = gi;
  }
  if (contiguous) return { groups, order: null };
  // Order present ⇒ it alone defines the balls, so drop the counts rather than ship a second,
  // independently-corruptible copy of the same fact.
  for (const g of groups) g[1] = 0;
  return { groups, order: groups.length <= 36 ? order.map(i => i.toString(36)).join("") : order };
}
function decBalls(groups, order) {
  const mk = g => ({ id: uid(), label: g[0], color: decColor(g[2]) });
  if (order == null) {
    const out = [];
    for (const g of groups) for (let i = 0; i < (g[1] || 0); i++) out.push(mk(g));
    return out;
  }
  const idx = typeof order === "string" ? [...order].map(c => parseInt(c, 36)) : order;
  return idx.map(i => mk(groups[i] || groups[0]));
}

function encDevice(device, stageVarName) {
  const t = TYPES.indexOf(device.type);
  const wr = device.withReplacement ? 1 : 0;
  const extra = {};
  // The stage's varName is the column identity; a device's own name is vestigial and usually
  // identical, so only carry it when it actually differs (a forked stage's branch devices).
  if (device.varName && device.varName !== stageVarName) extra.v = device.varName;
  let entries;
  if (device.type === "spinner") entries = (device.slices || []).map(s => [s.label, round4(s.pct), encColor(s.color)]);
  else if (device.type === "stacks") entries = (device.items || []).map(s => [s.label, s.count, encColor(s.color)]);
  else {
    const { groups, order } = encBalls(device.balls);
    entries = groups;
    if (order != null) extra.o = order;
  }
  const out = [t < 0 ? 0 : t, wr, entries];
  if (Object.keys(extra).length) out.push(extra);
  return out;
}
function decDevice(d, stageVarName) {
  const [t, wr, entries, extra] = d;
  const type = TYPES[t] || "spinner";
  const base = { id: uid(), type, varName: (extra && extra.v) || stageVarName, withReplacement: !!wr };
  const es = entries || [];
  if (type === "spinner") return { ...base, slices: es.map(e => ({ id: uid(), label: e[0], pct: e[1], color: decColor(e[2]) })) };
  if (type === "stacks") return { ...base, items: es.map(e => ({ id: uid(), label: e[0], count: e[1], color: decColor(e[2]) })) };
  return { ...base, balls: decBalls(es, extra ? extra.o : null) };
}

// Ids are DROPPED: a stage's identity in the blob is its position, so a branch condition
// stores the upstream stage's INDEX. Decode mints fresh uids and rewires the references,
// which is why applyConfig's migratePipeline/rekey* stay identity no-ops on a shared link.
function encPipeline(stages) {
  const at = new Map(stages.map((s, i) => [s.id, i]));
  return stages.map(st => [st.varName, (st.branches || []).map(b => {
    const dev = encDevice(b.device, st.varName);
    return b.condVar == null || !at.has(b.condVar) ? [dev] : [dev, at.get(b.condVar), b.condVal];
  })]);
}
function decPipeline(arr) {
  const ids = arr.map(() => uid());
  return arr.map(([varName, branches], i) => ({
    id: ids[i], type: "stage", varName,
    branches: (branches || []).map(b => {
      const [dev, condIdx, condVal] = b;
      const cond = condIdx != null && ids[condIdx] !== undefined;
      return { id: uid(), condVar: cond ? ids[condIdx] : null, condVal: cond ? condVal : null, device: decDevice(dev, varName) };
    }),
  }));
}

function encCompact(state) {
  const stages = stripSource(state.pipeline);
  const at = new Map(stages.map((s, i) => [s.id, i]));
  const opts = {};
  if (state.sampleSize !== DEFAULT_N) opts.n = state.sampleSize;
  if (state.runMode === "until") opts.u = 1;
  if (state.codeLang && state.codeLang !== "off") opts.l = state.codeLang;
  const r = state.stopRule;
  if (r && at.has(r.stageId)) {
    const k = STOP_KINDS.indexOf(r.kind);
    opts.r = [k < 0 ? 0 : k, at.get(r.stageId), r.value, r.n];
  }
  const out = [encPipeline(stages)];
  if (Object.keys(opts).length) out.push(opts);
  return JSON.stringify(out);
}
function decCompact(json) {
  const arr = JSON.parse(json);
  if (!Array.isArray(arr) || !Array.isArray(arr[0])) return null;
  const pipeline = decPipeline(arr[0]);
  const o = arr[1] || {};
  let stopRule = null;
  if (Array.isArray(o.r)) {
    const [k, idx, value, n] = o.r;
    const st = pipeline[idx];
    if (st) stopRule = { kind: STOP_KINDS[k] || "outcome", stageId: st.id, value, n };
  }
  return {
    pipeline,
    sampleSize: typeof o.n === "number" ? o.n : DEFAULT_N,
    runMode: o.u ? "until" : "fixed",
    stopRule,
    codeLang: o.l || undefined,
  };
}

// ─── Hidden (password-veiled) helpers — NOT crypto-grade ──────────────────────
// A hidden link opens and RUNS for anyone (its config is recoverable with the code-known
// PEPPER, not the password); the password only gates REVEALING the device internals in the
// UI. So the blob carries the obfuscated config PLUS a password verifier (a salted, stretched
// hash) — never the plaintext password. Reveal recomputes the verifier and compares. This is
// just enough to deter casual peeking at a shared population sampler.
function deriveKey(password, salt) {
  // Cheap, dependency-free key stretch: FNV-style fold of password+salt into a fixed
  // 64-char printable-ASCII keystream. (Deterministic; not a KDF — see note above.)
  const seed = password + "::" + salt;
  let h = 2166136261 >>> 0;
  let out = "";
  for (let i = 0; i < 64; i++) {
    h ^= seed.charCodeAt(i % seed.length) || 0;
    h = Math.imul(h, 16777619) >>> 0;
    out += String.fromCharCode(33 + (h % 94)); // printable ASCII, < 128
  }
  return out;
}
// Veil the COMPRESSED blob by shifting each char within lz-string's own URI-safe alphabet.
// Order matters: XOR-then-compress (the v1 mistake) hands the compressor pseudo-random bytes
// it cannot pack, then pays base64 +33% and 6 bytes per JSON-escaped control char — which is
// why v1 hidden links ran ~20× longer than they needed to. Compress first, veil second, and
// the output is already URL-safe.
function xorAlpha(str, key, dir) {
  let out = "";
  for (let i = 0; i < str.length; i++) {
    const a = ALPHA.indexOf(str[i]);
    if (a < 0) { out += str[i]; continue; }
    const shift = key.charCodeAt(i % key.length) % 64;
    out += ALPHA[(a + dir * shift + 64) % 64];
  }
  return out;
}
function randomSalt() {
  return Math.random().toString(36).slice(2, 10).padEnd(8, "0"); // base36 ⇒ already URL-safe
}
// Fold an arbitrary printable-ASCII string into the URI-safe alphabet. deriveKey's keystream
// spans ASCII 33-126, which includes '#', '&', '+' and '%' — fine inside v1's JSON envelope
// (it got compressed into the safe alphabet afterwards), but v2 puts the verifier DIRECTLY in
// the query string, where a '#' would truncate the whole link.
const toAlpha = s => [...s].map(c => ALPHA[c.charCodeAt(0) % 64]).join("");
// Password verifier stored in a hidden blob so Reveal can check the password without keeping
// it. A salted, stretched derivation of the password (deterministic ⇒ a correct password
// reproduces the same string); the plaintext never travels.
function pwVerifier(password, salt) {
  return toAlpha(deriveKey(password, salt + "::pw"));
}

// Encode app state → a URL-safe blob string (the value of the ?s= param).
// opts.password (optional) produces a HIDDEN blob: the config is concealed behind the
// password while the sampler still runs for whoever opens the link.
export function encodeConfig(state, opts) {
  const lz = LZString.compressToEncodedURIComponent(encCompact(state));
  const password = opts && opts.password;
  if (!password) return "P" + lz;
  const salt = randomSalt();
  // Obfuscate with a code-known key (NOT the password) so the sampler runs for anyone who
  // opens the link; store a password verifier so Reveal can gate viewing the internals.
  return "H" + salt + pwVerifier(password, salt).slice(0, PW_LEN) + xorAlpha(lz, deriveKey(PEPPER, salt), 1);
}

// Decode a blob → one of:
//   null                                  (absent/garbled)
//   { stale:true }                        (a v1 link — readable shape, unsupported format)
//   { hidden:false, config }              (ready to load)
//   { hidden:true, salt, pw, config }     (load+run concealed at once — no password needed;
//                                          `salt`+`pw` gate a later Reveal via
//                                          checkHiddenPassword)
export function decodeConfig(blob) {
  if (!blob) return null;
  // '+' is a legal char in lz-string's URI-safe alphabet but decodes to a space out of a query
  // string, so restore it. (lz-string does this internally for the plain path; the hidden path
  // un-veils before decompressing, so it has to happen up front for both.)
  blob = blob.replace(/ /g, "+");
  try {
    if (blob[0] === "P") {
      const config = decCompact(LZString.decompressFromEncodedURIComponent(blob.slice(1)));
      return config ? { hidden: false, config } : null;
    }
    if (blob[0] === "H") {
      const salt = blob.slice(1, 9);
      const pw = blob.slice(9, 9 + PW_LEN);
      const lz = xorAlpha(blob.slice(9 + PW_LEN), deriveKey(PEPPER, salt), -1);
      const config = decCompact(LZString.decompressFromEncodedURIComponent(lz));
      return config ? { hidden: true, salt, pw, config } : null;
    }
    // No marker: either garbage or a v1 link (an lz-compressed JSON envelope). v1 is a clean
    // break — but recognizing it lets the app say "too old" instead of silently opening a
    // blank sampler, which is what a stale link in a syllabus would otherwise look like.
    const json = LZString.decompressFromEncodedURIComponent(blob);
    if (json && json[0] === "{" && /"v"\s*:/.test(json)) return { stale: true };
    return null;
  } catch { return null; }
}

// Reveal gate: verify a password against the stored verifier. The plaintext password is
// never stored or transmitted — only this salted, stretched derivation is compared. Compares
// only as many chars as the blob carries (v2 stores a truncated prefix).
export function checkHiddenPassword(salt, pwStored, password) {
  return !!salt && !!pwStored && pwVerifier(password, salt).slice(0, pwStored.length) === pwStored;
}

// Build a full shareable URL for the current page from a blob.
export function shareURL(blob) {
  const base = window.location.origin + window.location.pathname;
  return base + "?s=" + blob;
}
